name: Node-Red-S1Seven-API CI

on:
    push:
        paths-ignore:
            - 'README.md'
            - 'package-lock.json'
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
        paths-ignore:
            - 'README.md'
            - 'package-lock.json'
        branches:
            - main

jobs:
    setup-and-test:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run Jest tests
              run: npm test
              env:
                  CI: true
